config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'
  get    '/signup',  to: 'users#new'

  root'users#home'
  get '/users', to:'users#home'
  get '/secret_page', to: 'users#secret_page'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  include SessionsHelper

end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :email, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
      #redirect_to "/images/screenshot.jpg"
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def secret_page
  end
   
  def home
  end

  def new
    @user = User.new
  end

  def create
    @user =  User.new(user_params)
    if @user.save
      #fait appel à la fonction show avec l'id du user
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to @user
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to users_path
  end



  private
    def user_params
      params.require(:user).permit(:email, :password)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html >
  <head>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <title>Secret</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul>
      <% if logged_in? %>
        <li><h4><strong><%= link_to "Log out", logout_path, method: :delete %></strong></h4></li>
      <% else %>
        <li><h4><strong><%= link_to "Log in", login_path %></strong></h4></li>
      <% end %>
    </ul>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>

    </div>

  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/home.html.erb
<div class="center jumbotron">
  <h1>Petit tour sur la Page ultra secrète?</h1>
  <h2><a href="secret_page"  >Clique ici!</a></h2>
</div>

app/views/users/new.html.erb
<% provide(:title, "Sign up")%>


<div class="row">

  <div class="col-md-6 col-md-offset-3">
    <h1>Sign up</h1>
    <%= form_for @user do |f| %>

      <%= f.label :Email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :Password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit "Sign up!", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/users/secret_page.html.erb
<div class="row">

  <div class="col-md-6 col-md-offset-3">
    <h3>Voici la reponse à la question grande question de l'univer! </h3>
    <% if logged_in? %>
       <h1><strong>La reponse est en chacun de nous!</strong></h1>
       <h1><strong> A toi de la trouver!</strong></h1>
    <% else %>
      <h4><strong><%= link_to "connecte toi pour tout savoir!", login_path %></strong></h4>
    <% end %>
    <p><%= link_to "Back to home?", root_path %></p>
  </div>
</div>

app/views/users/show.html.erb
<div class="center jumbotron">
	<h1> Le profil de <%= @user.email%></h1>
<ul>
	<li> <strong>Email :</strong> <%= @user.email %> </li>
</ul>

<br><br><%= link_to "[Editer]", edit_user_path(@user) %>
<%= link_to "[Supprimer]", user_path(@user),
              method: :delete,
              data: { confirm: 'Es-tu sûr ?' } %>
<%= link_to "[Retour à l'index]", users_path %>

</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>